/**
 * Builder worktree write-guard (Issue #1018).
 *
 * A strict-mode builder runs in a git worktree nested inside the main checkout.
 * The Write/Edit tools require absolute paths, so the model must *synthesize*
 * one. When the runtime anchors that path at the inferred canonical repo root
 * instead of the worktree cwd, the `.builders/<id>/` segment is dropped and the
 * write silently lands in the main checkout (a real, writable, byte-identical
 * sibling tree). Instructions/memory don't hold against this because it's
 * intrinsic path-synthesis behavior that drifts across model/CLI upgrades — only
 * a deterministic guard holds.
 *
 * This module is the single source of truth for the guard. It emits two files
 * into each Claude builder worktree at spawn time (via CLAUDE_HARNESS):
 *   - `.claude/hooks/worktree-write-guard.cjs` — a self-contained Node hook
 *   - `.claude/settings.local.json` — a PreToolUse hook wiring on Write/Edit/Bash
 *
 * The hook denies any absolute Write/Edit path that resolves outside the
 * worktree root, with an allowlist for temp dirs and `$HOME/.claude` (so builder
 * memory/config writes still work). The worktree root is baked into the hook
 * command as `CODEV_WORKTREE_ROOT` (deterministic), with `git rev-parse
 * --show-toplevel` as a runtime fallback.
 *
 * Issue #1536 extends the same guard to Bash: reads and executions against the
 * wrong tree are the other, self-concealing half of the threat model (running
 * main's copy yields plausible-but-wrong results, not an error). The guard
 * already knows both roots, so for a Bash command it does not parse the shell —
 * it searches the command for literal occurrences of the main-checkout root and
 * denies any that fall outside the worktree. A match that continues into the
 * worktree's own `.builders/<id>/` tail is allowed as-written, which naturally
 * covers the spawn-created worktree symlinks into main (`.env`,
 * `.codev/config.json`, `worktree.symlinks`) with no realpath needed. A
 * per-command sentinel comment (`codev:allow-main-checkout`) is a deliberate,
 * non-sticky escape hatch for the rare legitimate main-checkout reference.
 *
 * @see codev/plans/1018-builder-worktree-write-guard-p.md
 * @see codev/plans/1536-builder-bash-commands-can-sile.md
 */

import { isAbsolute, join, resolve } from 'node:path';

/** Worktree-relative path of the emitted guard script. */
export const GUARD_SCRIPT_RELPATH = '.claude/hooks/worktree-write-guard.cjs';

/** Worktree-relative path of the emitted settings file. */
export const GUARD_SETTINGS_RELPATH = '.claude/settings.local.json';

/**
 * The self-contained Node guard script, emitted verbatim into each worktree.
 *
 * Kept as a string constant (not a separate asset) so it ships with the
 * compiled package automatically — `tsc` does not copy non-TS files to `dist`.
 * It is exercised directly by the unit test, which writes it to a temp `.cjs`
 * and spawns it with fixture stdin, so the constant is the tested artifact.
 *
 * Self-contained: no `require` of any project code (worktrees have no access to
 * the package's node_modules, and neither do adopter repos). Node core only.
 *
 * Fail-open by design: any error (bad JSON, missing root, unexpected shape)
 * allows the tool call. A safety net must never brick a builder session; the
 * worst case of a failure is reverting to today's unguarded behavior.
 */
export const WORKTREE_WRITE_GUARD_SCRIPT = `#!/usr/bin/env node
// AUTO-GENERATED by @cluesmith/codev (Issue #1018). Do not edit in the worktree;
// edit packages/codev/src/agent-farm/utils/worktree-write-guard.ts instead.
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

// Write-family tools whose file_path we guard (canonicalize-first: resolving a
// symlink is correct here, because writing THROUGH a link into main mutates
// main's file). Bash is guarded separately below (lexical-first). NotebookEdit
// (notebook_path) is out of scope.
const GUARDED_WRITE_TOOLS = new Set(['Write', 'Edit', 'MultiEdit']);

// Per-command escape hatch for the rare legitimate main-checkout reference from
// Bash. A sentinel COMMENT (not an env toggle) so it is scoped to exactly one
// command and visible in the transcript, never sticky. Intentionally NOT named
// in the deny message, so it is not reached for reflexively.
const MAIN_CHECKOUT_ESCAPE = 'codev:allow-main-checkout';

function allow() {
  process.exit(0);
}

function emitDeny(reason) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

function deny(target, root) {
  emitDeny(
    'Blocked: ' + target + ' is outside this builder\\'s worktree (' + root + '). ' +
    'Builders are isolated to their worktree — a path anchored at the main checkout ' +
    'root silently pollutes it. Re-root the path under ' + root +
    ' (prefer a worktree-relative path). Allowed exceptions: temp dirs and ~/.claude.'
  );
}

function denyBash(target, worktreeRoot, mainRoot) {
  emitDeny(
    'Blocked: this Bash command references ' + target + ', which is in the main ' +
    'checkout (' + mainRoot + ') but OUTSIDE this builder\\'s worktree (' + worktreeRoot +
    '). A path that drops the .builders/<id>/ segment silently reads or runs against ' +
    'main\\'s copy and yields plausible-but-wrong results (missing test suites, stale ' +
    'behavior). Use a relative path (cwd is your worktree) or re-root the path under ' +
    worktreeRoot + '.'
  );
}

// Resolve a path to a canonical absolute form WITHOUT requiring it to exist:
// realpath the longest existing ancestor (resolving symlinks, e.g. macOS
// /tmp -> /private/tmp), then re-append the non-existent tail.
function canonicalize(p, cwd) {
  let abs = path.isAbsolute(p) ? p : path.resolve(cwd, p);
  abs = path.normalize(abs);
  let tail = '';
  let cur = abs;
  for (;;) {
    try {
      const real = fs.realpathSync(cur);
      return tail ? path.join(real, tail) : real;
    } catch (e) {
      const parent = path.dirname(cur);
      if (parent === cur) {
        return abs;
      }
      tail = tail ? path.join(path.basename(cur), tail) : path.basename(cur);
      cur = parent;
    }
  }
}

function isInside(child, parent) {
  if (!parent) {
    return false;
  }
  if (child === parent) {
    return true;
  }
  return child.startsWith(parent + path.sep);
}

// Worktree root: baked-in env (deterministic) first, then git as a fallback.
function worktreeRootFor(cwd) {
  let root = process.env.CODEV_WORKTREE_ROOT;
  if (!root) {
    try {
      root = execSync('git rev-parse --show-toplevel', { cwd, encoding: 'utf8' }).trim();
    } catch (e) {
      root = '';
    }
  }
  return root;
}

// Main checkout = the worktree path with its trailing '/.builders/<id>' removed.
// Uses the LAST '/.builders/' so the derived root is correct (and the deny
// message accurate) even when the main checkout's own path contains '.builders'.
// Returns '' when the worktree is not a nested .builders worktree (nothing to
// compare a Bash path against).
function mainCheckoutFor(worktreeRoot) {
  const norm = path.normalize(worktreeRoot);
  const marker = path.sep + '.builders' + path.sep;
  const idx = norm.lastIndexOf(marker);
  if (idx === -1) {
    return '';
  }
  return norm.slice(0, idx);
}

// True at a shell "edge": the empty string (start or end of the command) or any
// char that cannot be part of a path (whitespace, quotes, redirections, list and
// pipe operators, and the assignment/separator chars that can prefix a path).
// Used ONLY to check that a matched main-root occurrence sits on a real path
// boundary — never to tokenize the command.
function isBoundary(ch) {
  return ch === '' || ch <= ' ' || ch === "'" || ch === '"' ||
    ch === '(' || ch === ')' || ch === '|' || ch === '&' || ch === ';' ||
    ch === '<' || ch === '>' || ch === '\`' || ch === '$' || ch === '=' ||
    ch === ',' || ch === ':';
}

function guardWrite(input, cwd) {
  const toolInput = (input && input.tool_input) || {};
  const filePath = toolInput.file_path;
  if (!filePath || typeof filePath !== 'string') {
    return allow();
  }

  let root = worktreeRootFor(cwd);
  if (!root) {
    // Can't determine the boundary — fail open rather than block every write.
    return allow();
  }
  root = canonicalize(root, cwd);

  const target = canonicalize(filePath, cwd);

  if (isInside(target, root)) {
    return allow();
  }

  // Allowlist: temp dirs (scratch) and ~/.claude (builder memory + config).
  const allowRoots = [];
  const addAllow = (p) => {
    if (p) {
      allowRoots.push(canonicalize(p, cwd));
    }
  };
  addAllow('/tmp');
  addAllow('/private/tmp');
  addAllow(process.env.TMPDIR);
  if (process.env.HOME) {
    addAllow(path.join(process.env.HOME, '.claude'));
  }

  for (const a of allowRoots) {
    if (isInside(target, a)) {
      return allow();
    }
  }

  return deny(target, root);
}

function guardBash(input, cwd) {
  const toolInput = (input && input.tool_input) || {};
  const command = toolInput.command;
  if (!command || typeof command !== 'string') {
    return allow();
  }

  // Per-command escape hatch: a deliberate main-checkout reference stays possible.
  if (command.indexOf(MAIN_CHECKOUT_ESCAPE) !== -1) {
    return allow();
  }

  const worktreeRoot = worktreeRootFor(cwd);
  if (!worktreeRoot) {
    // Can't determine the boundary, fail open.
    return allow();
  }
  const worktreeNorm = path.normalize(worktreeRoot);
  const mainRoot = mainCheckoutFor(worktreeNorm);
  if (!mainRoot) {
    // Not a nested .builders worktree, nothing to compare against.
    return allow();
  }

  // We already KNOW both roots, so there is no need to parse the shell. We search
  // the command for literal occurrences of the main-checkout root and inspect the
  // boundaries of each match. worktreeTail is the worktree expressed relative to
  // the main root, e.g. '/.builders/pir-1536'; a match that continues INTO this
  // tail is a worktree reference (allowed as-written, which also covers the
  // spawn-created worktree symlinks into main — no realpath needed). Anything else
  // under the main root is a wrong-tree reference.
  const sep = path.sep;
  const worktreeTail = worktreeNorm.slice(mainRoot.length);

  let from = 0;
  for (;;) {
    const idx = command.indexOf(mainRoot, from);
    if (idx === -1) {
      break;
    }
    from = idx + mainRoot.length;

    // The char before must be a boundary; otherwise the main root only matched
    // inside a longer name (e.g. mainRoot '/repo' inside '/x/repo-backup').
    if (!isBoundary(idx === 0 ? '' : command[idx - 1])) {
      continue;
    }

    const rest = command.slice(from);

    // A reference into (or exactly at) this worktree — allow. The char after the
    // tail must be a real boundary so 'pir-1536-backup' is not mistaken for the
    // 'pir-1536' worktree.
    if (rest.startsWith(worktreeTail)) {
      const afterTail = rest.length > worktreeTail.length ? rest[worktreeTail.length] : '';
      if (afterTail === '' || afterTail === sep || isBoundary(afterTail)) {
        continue;
      }
    }

    // A wrong-tree reference: the main root at end-of-path — a subpath
    // ('/repo/apps') or the bare root at an edge ('cd /repo && ...'). If the next
    // char is a non-sep path char, the main root was again only a prefix of a
    // longer name and this is not a real match.
    const next = rest.length ? rest[0] : '';
    if (next !== '' && next !== sep && !isBoundary(next)) {
      continue;
    }

    // Extract the offending path (up to the next boundary) for the message.
    let end = 0;
    while (end < rest.length && !isBoundary(rest[end])) {
      end++;
    }
    return denyBash(mainRoot + rest.slice(0, end), worktreeNorm, mainRoot);
  }

  return allow();
}

function main(raw) {
  let input;
  try {
    input = JSON.parse(raw);
  } catch (e) {
    return allow();
  }

  const toolName = input && input.tool_name;
  const cwd = (input && input.cwd) || process.cwd();

  if (GUARDED_WRITE_TOOLS.has(toolName)) {
    return guardWrite(input, cwd);
  }
  if (toolName === 'Bash') {
    return guardBash(input, cwd);
  }
  return allow();
}

let buf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (d) => {
  buf += d;
});
process.stdin.on('end', () => {
  try {
    main(buf);
  } catch (e) {
    // Never brick a session on an unexpected error.
    allow();
  }
});
`;

/** Single-quote-escape a value for safe embedding in a POSIX shell command. */
function shellSingleQuote(value: string): string {
  return value.replace(/'/g, `'\\''`);
}

/**
 * Build the worktree files that install the write-guard for a Claude builder.
 *
 * @param worktreePath absolute path to the builder's worktree
 * @returns files (relativePath + content) for writeWorktreeFiles()
 */
export function buildWorktreeGuardFiles(
  worktreePath: string,
): Array<{ relativePath: string; content: string }> {
  const root = isAbsolute(worktreePath) ? worktreePath : resolve(worktreePath);
  const scriptAbs = join(root, GUARD_SCRIPT_RELPATH);

  // Bake the worktree root in (deterministic) and run via `node` so the emitted
  // script needs no executable bit.
  const command =
    `CODEV_WORKTREE_ROOT='${shellSingleQuote(root)}' ` +
    `node '${shellSingleQuote(scriptAbs)}'`;

  const settings = {
    hooks: {
      PreToolUse: [
        {
          matcher: 'Write|Edit|MultiEdit|Bash',
          hooks: [{ type: 'command', command }],
        },
      ],
    },
  };

  return [
    { relativePath: GUARD_SCRIPT_RELPATH, content: WORKTREE_WRITE_GUARD_SCRIPT },
    { relativePath: GUARD_SETTINGS_RELPATH, content: JSON.stringify(settings, null, 2) + '\n' },
  ];
}
