/**
 * Shadow-tree removal equivalence (Spec 1252, M10 / T9).
 *
 * Phase 4 deleted 77 shadow copies from `codev/protocols|roles|consult-types`.
 * The entire claim of that deletion is that it is a NO-OP for what agents are
 * served: after Phases 3 and 4b reconciled every survivor to the skeleton, the
 * resolver must now return the skeleton counterpart for every deleted path,
 * with content byte-identical to what was resolved immediately before
 * deletion (captured in `fixtures/shadow-removal-manifest.json`).
 *
 * Assembled-prompt equivalence (M10 clause ii) is verified DIRECTLY, not
 * inferred: `fixtures/prompt-snapshots/<protocol>.txt` were generated by
 * running the real assembly path (`buildPromptFromTemplate`, which loads the
 * resolved builder-prompt.md, inlines protocol.md via {{protocol_reference}},
 * and renders) against the PRE-DELETION tree reconstructed from git
 * (`git archive adae5f3b^`), under a fixed TemplateContext. The test re-runs
 * the same assembly against the live tree and requires byte-identical output.
 * (The first draft inferred this from content hashes + renderTemplate purity;
 * Codex's phase review correctly demanded the assembly path be exercised.)
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { createHash } from 'node:crypto';
import { resolveCodevFile, getSkeletonDir } from '../lib/skeleton.js';
import {
  buildPromptFromTemplate,
  type TemplateContext,
} from '../agent-farm/commands/spawn-roles.js';

const REPO_ROOT = path.resolve(__dirname, '../../../..');
const MANIFEST: Record<string, string> = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, 'fixtures/shadow-removal-manifest.json'), 'utf-8')
);

const sha = (p: string) => createHash('sha256').update(fs.readFileSync(p)).digest('hex');

describe('shadow-removal equivalence (M10)', () => {
  it('manifest covers all 77 deleted shadow copies', () => {
    expect(Object.keys(MANIFEST).length).toBe(77);
  });

  it('every deleted path resolves to the skeleton with pre-deletion content', () => {
    const mismatches: string[] = [];
    for (const [rel, expectedSha] of Object.entries(MANIFEST)) {
      // (i) the local copy must be gone — tier 2 no longer shadows tier 4
      const local = path.join(REPO_ROOT, 'codev', rel);
      if (fs.existsSync(local)) {
        mismatches.push(`${rel}: local shadow copy still exists`);
        continue;
      }
      // (ii) the resolver must serve the file FROM THE SKELETON TIER — path
      // identity, not just content identity (M10 requires proving where
      // resolution lands; a content match from some other tier would hide a
      // resolution bug)
      const resolved = resolveCodevFile(rel, REPO_ROOT);
      if (!resolved) {
        mismatches.push(`${rel}: resolver returned nothing after deletion`);
        continue;
      }
      const skeletonPath = path.join(getSkeletonDir(), rel);
      if (path.resolve(resolved) !== path.resolve(skeletonPath)) {
        mismatches.push(`${rel}: resolved to ${resolved}, expected skeleton tier ${skeletonPath}`);
        continue;
      }
      // (iii) content must be byte-identical to what was served pre-deletion
      if (sha(resolved) !== expectedSha) {
        mismatches.push(`${rel}: resolved content differs from pre-deletion snapshot`);
      }
    }
    expect(
      mismatches,
      mismatches.length
        ? `Deletion was NOT a no-op:\n` + mismatches.map((m) => `  - ${m}`).join('\n')
        : undefined
    ).toEqual([]);
  });

  /**
   * M10 clause (ii): assembled-prompt byte-equivalence, via the REAL assembly
   * path. Snapshots were generated against the pre-deletion tree (git archive
   * of the parent of the deletion commit) with this exact fixed context; the
   * live assembly must reproduce them byte-for-byte.
   */
  const FIXED_CTX: TemplateContext = {
    protocol_name: 'PROTO',
    mode: 'strict',
    mode_soft: false,
    mode_strict: true,
    project_id: '9999',
    input_description: 'M10 equivalence fixture — fixed context',
    issue: { number: 9999, title: 'fixture', body: 'fixture body' },
  };
  const SNAPSHOT_PROTOCOLS = [
    'air', 'aspir', 'bugfix', 'experiment', 'maintain', 'pir', 'research', 'spike', 'spir',
  ];

  it('assembled spawn prompts are byte-identical to pre-deletion snapshots', () => {
    for (const proto of SNAPSHOT_PROTOCOLS) {
      const snapshot = fs.readFileSync(
        path.resolve(__dirname, `fixtures/prompt-snapshots/${proto}.txt`),
        'utf-8'
      );
      const live = buildPromptFromTemplate(
        { workspaceRoot: REPO_ROOT } as never,
        proto,
        { ...FIXED_CTX, protocol_name: proto }
      );
      expect(live, `${proto}: assembled prompt changed across the deletion`).toBe(snapshot);
    }
  });

  it('local-only entries survived and still resolve (M8 preservation / T8)', () => {
    const preserved = [
      'protocols/release/protocol.md',
      'protocols/maintain/templates/audit-report.md',
      'protocols/maintain/templates/lessons-learned.md',
    ];
    for (const rel of preserved) {
      const local = path.join(REPO_ROOT, 'codev', rel);
      expect(fs.existsSync(local), `${rel} must survive deletion`).toBe(true);
      // and the resolver serves the local copy (they have no skeleton counterpart)
      expect(resolveCodevFile(rel, REPO_ROOT)).toBe(local);
    }
  });
});
